
del armor_not_pierced_by_player_12.wav
del armor_not_pierced_by_player_13.wav
del armor_not_pierced_by_player_14.wav
del armor_not_pierced_by_player_15.wav
del armor_not_pierced_by_player_16.wav
del armor_not_pierced_by_player_17.wav
del armor_not_pierced_by_player_18.wav
del armor_not_pierced_by_player_19.wav
del armor_not_pierced_by_player_20.wav

del armor_pierced_by_player_06.wav
del armor_pierced_by_player_07.wav
del armor_pierced_by_player_08.wavdel armor_pierced_by_player_09.wav
del armor_pierced_by_player_10.wav
del armor_pierced_by_player_11.wav
del armor_pierced_by_player_12.wav
del armor_pierced_by_player_13.wav
del armor_pierced_by_player_14.wav
del armor_pierced_by_player_15.wav
del armor_pierced_by_player_16.wav

del damage_by_near_explosion_by_player_06.wav
del damage_by_near_explosion_by_player_07.wav
del damage_by_near_explosion_by_player_08.wav

del start_battle_21.wav
del start_battle_22.wav
del start_battle_23.wav
del start_battle_24.wav
del start_battle_25.wav
del start_battle_26.wav
del start_battle_27.wav
del start_battle_28.wav
del start_battle_29.wav
del start_battle_30.wav
del start_battle_31.wav
del start_battle_32.wav
del start_battle_33.wav
del start_battle_34.wav
del start_battle_35.wav
del start_battle_36.wav
del start_battle_37.wav
del start_battle_38.wav
del start_battle_39.wav
del start_battle_40.wav
del start_battle_41.wav

del vehicle_destroyed_06.wav
del vehicle_destroyed_07.wav
del vehicle_destroyed_08.wav
del vehicle_destroyed_09.wav
del vehicle_destroyed_10.wav
del vehicle_destroyed_11.wav
del vehicle_destroyed_12.wav
del vehicle_destroyed_13.wav
del vehicle_destroyed_14.wav
del vehicle_destroyed_15.wav
del vehicle_destroyed_16.wav
del vehicle_destroyed_17.wav
del vehicle_destroyed_18.wav
del vehicle_destroyed_19.wav
del vehicle_destroyed_20.wav
del vehicle_destroyed_21.wav
del vehicle_destroyed_22.wav
del vehicle_destroyed_23.wav
del vehicle_destroyed_24.wav
del vehicle_destroyed_25.wav
