
copy armor_not_pierced_by_player_01.wav armor_not_pierced_by_player_06.wav
copy armor_not_pierced_by_player_02.wav armor_not_pierced_by_player_07.wav
copy armor_not_pierced_by_player_03.wav armor_not_pierced_by_player_08.wav
copy armor_not_pierced_by_player_04.wav armor_not_pierced_by_player_09.wav
copy armor_not_pierced_by_player_05.wav armor_not_pierced_by_player_10.wav
copy armor_not_pierced_by_player_06.wav armor_not_pierced_by_player_11.wav
copy armor_not_pierced_by_player_07.wav armor_not_pierced_by_player_12.wav

copy armor_pierced_by_player_01.wav armor_pierced_by_player_06.wav
copy armor_pierced_by_player_02.wav armor_pierced_by_player_07.wav
copy armor_pierced_by_player_03.wav armor_pierced_by_player_08.wav
copy armor_pierced_by_player_04.wav armor_pierced_by_player_09.wav
copy armor_pierced_by_player_05.wav armor_pierced_by_player_10.wav
copy armor_pierced_by_player_06.wav armor_pierced_by_player_11.wav
copy armor_pierced_by_player_07.wav armor_pierced_by_player_12.wav

copy damage_by_near_explosion_by_player_01.wav damage_by_near_explosion_by_player_06.wav
copy damage_by_near_explosion_by_player_02.wav damage_by_near_explosion_by_player_07.wav
copy damage_by_near_explosion_by_player_03.wav damage_by_near_explosion_by_player_08.wav
copy damage_by_near_explosion_by_player_04.wav damage_by_near_explosion_by_player_09.wav

copy enemy_killed_by_player_01.wav enemy_killed_by_player_11.wav
copy enemy_killed_by_player_02.wav enemy_killed_by_player_12.wav
copy enemy_killed_by_player_03.wav enemy_killed_by_player_13.wav
copy enemy_killed_by_player_04.wav enemy_killed_by_player_14.wav
copy enemy_killed_by_player_05.wav enemy_killed_by_player_15.wav

copy start_battle_01.wav start_battle_21.wav
copy start_battle_02.wav start_battle_22.wav
copy start_battle_03.wav start_battle_23.wav
copy start_battle_04.wav start_battle_24.wav
copy start_battle_05.wav start_battle_25.wav
copy start_battle_06.wav start_battle_26.wav
copy start_battle_07.wav start_battle_27.wav
copy start_battle_08.wav start_battle_28.wav
copy start_battle_09.wav start_battle_29.wav
copy start_battle_10.wav start_battle_30.wav
copy start_battle_11.wav start_battle_31.wav
copy start_battle_12.wav start_battle_32.wav
copy start_battle_13.wav start_battle_33.wav
copy start_battle_14.wav start_battle_34.wav
copy start_battle_15.wav start_battle_35.wav
copy start_battle_16.wav start_battle_36.wav
copy start_battle_17.wav start_battle_37.wav
copy start_battle_18.wav start_battle_38.wav
copy start_battle_19.wav start_battle_39.wav
copy start_battle_20.wav start_battle_40.wav
copy start_battle_21.wav start_battle_41.wav
copy start_battle_22.wav start_battle_42.wav
copy start_battle_23.wav start_battle_43.wav
copy start_battle_24.wav start_battle_44.wav
copy start_battle_25.wav start_battle_45.wav
copy start_battle_26.wav start_battle_46.wav
copy start_battle_27.wav start_battle_47.wav
copy start_battle_28.wav start_battle_48.wav
copy start_battle_29.wav start_battle_49.wav
copy start_battle_30.wav start_battle_50.wav
copy start_battle_31.wav start_battle_51.wav
copy start_battle_32.wav start_battle_52.wav
copy start_battle_33.wav start_battle_53.wav

copy target_lost_01.wav target_lost_05.wav

copy track_destroyed_01.wav track_destroyed_05.wav
copy track_destroyed_02.wav track_destroyed_06.wav

copy vehicle_destroyed_01.wav vehicle_destroyed_06.wav
copy vehicle_destroyed_02.wav vehicle_destroyed_07.wav
copy vehicle_destroyed_03.wav vehicle_destroyed_08.wav
copy vehicle_destroyed_04.wav vehicle_destroyed_09.wav
copy vehicle_destroyed_05.wav vehicle_destroyed_10.wav
copy vehicle_destroyed_06.wav vehicle_destroyed_11.wav
copy vehicle_destroyed_07.wav vehicle_destroyed_12.wav
copy vehicle_destroyed_08.wav vehicle_destroyed_13.wav
copy vehicle_destroyed_09.wav vehicle_destroyed_14.wav
copy vehicle_destroyed_10.wav vehicle_destroyed_15.wav
copy vehicle_destroyed_11.wav vehicle_destroyed_16.wav
copy vehicle_destroyed_12.wav vehicle_destroyed_17.wav
copy vehicle_destroyed_13.wav vehicle_destroyed_18.wav
copy vehicle_destroyed_14.wav vehicle_destroyed_19.wav
copy vehicle_destroyed_15.wav vehicle_destroyed_20.wav
copy vehicle_destroyed_16.wav vehicle_destroyed_21.wav
copy vehicle_destroyed_17.wav vehicle_destroyed_22.wav
copy vehicle_destroyed_18.wav vehicle_destroyed_23.wav
copy vehicle_destroyed_19.wav vehicle_destroyed_24.wav
copy vehicle_destroyed_20.wav vehicle_destroyed_25.wav
